# Generated by Django 4.0.6 on 2022-07-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tron_api', '0002_alter_wallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='Username',
            field=models.CharField(default='Simon', max_length=200),
            preserve_default=False,
        ),
    ]
