# Generated by Django 4.0.6 on 2022-07-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tron_api', '0003_wallet_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Username',
            new_name='email_address',
        ),
        migrations.AddField(
            model_name='wallet',
            name='password',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
