# Generated by Django 4.0.6 on 2022-07-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tron_api', '0006_dev_data_delete_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dev_data',
            old_name='PRIVATE_KEY',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='dev_data',
            old_name='WALLET_ADDRESS',
            new_name='wallet_address',
        ),
    ]
